on: workflow_dispatch
name: 🚀 Deploy website live manually
jobs:
  web-deploy:
    name: 🎉 Deploy live
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_URL_PUBLIC }}
        username: todo_public
        password: ${{ secrets.FTP_PASS_PUBLIC }}
